---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
# icons found here https://github.com/walkxcode/dashboard-icons

- Hypervisor:
    - Proxmox:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        description: pve1
        widget:
          type: proxmox
          url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
          username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
          node: xing-01
    - Proxmox:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        description: pve2
        widget:
          type: proxmox
          url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
          username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
          node: xing-02
    - Proxmox:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        description: pve2
        widget:
          type: proxmox
          url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
          username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
          node: xing-03
    - Proxmox:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        description: pve4
        widget:
          type: proxmox
          url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
          username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
          node: storinator
- Containers:
    - Rancher:
        icon: rancher.svg
        href: "{{HOMEPAGE_VAR_RACNHER_URL}}"
        description: k8s
    - Longhorn:
        icon: longhorn.svg
        href: "{{HOMEPAGE_VAR_LONGHORN_URL}}"
        description: k8s storage
    - Portainer:
        icon: portainer.svg
        href: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
        description: docker
        widget:
          type: portainer
          url: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
          env: 2
          key: "{{HOMEPAGE_VAR_PORTAINER_API_KEY}}"
    - Dozzle:
        icon: dozzle.svg
        href: "{{HOMEPAGE_VAR_DOZZLE_URL}}"
        description: container logs
    - Homepage:
        icon: homepage.svg
        href: "{{HOMEPAGE_VAR_HOMEPAGE_URL}}"
        description: dashboard
    - Socket-Proxy:
        icon: socket-proxy.svg
        href: "{{HOMEPAGE_VAR_SOCKET_PROXY_URL}}"
        description: proxy service
    - Docker-GC:
        icon: docker-gc.svg
        href: "{{HOMEPAGE_VAR_DOCKER_GC_URL}}"
        description: container garbage collection
- DNS:
    - Pi-Hole1:
        icon: pi-hole.svg
        href: "{{HOMEPAGE_VAR_PIHOLE_URL_1}}"
        description: quasar
        widget:
          type: pihole
          url: "{{HOMEPAGE_VAR_PIHOLE_URL_1}}"
          key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY_1}}"
    - Pi-Hole2:
        icon: pi-hole.svg
        href: "{{HOMEPAGE_VAR_PIHOLE_URL_2}}"
        description: blazar
        widget:
          type: pihole
          url: "{{HOMEPAGE_VAR_PIHOLE_URL_2}}"
          key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY_2}}"
    - Pi-Hole3:
        icon: pi-hole.svg
        href: "{{HOMEPAGE_VAR_PIHOLE_URL_3}}"
        description: electron
        widget:
          type: pihole
          url: "{{HOMEPAGE_VAR_PIHOLE_URL_3}}"
          key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY_3}}"
- Network:
    - UniFi:
        icon: unifi.svg
        href: "{{HOMEPAGE_VAR_UNIFI_NETWORK_URL}}"
        description: network
        widget:
          type: unifi
          url: "{{HOMEPAGE_VAR_UNIFI_NETWORK_URL}}"
          username: "{{HOMEPAGE_VAR_UNIFI_NETWORK_USERNAME}}"
          password: "{{HOMEPAGE_VAR_UNIFI_NETWORK_PASSWORD}}"
    - Uptime Kuma:
        icon: uptime-kuma.svg
        href: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
        description: internal
        widget:
          type: uptimekuma
          url: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
          slug: home
    - Uptime Robot:
        icon: https://play-lh.googleusercontent.com/cUrv0t00FYQ1GKLuOTvv8qjo1lSDjqZC16IOp3Fb6ijew6Br5m4o16HhDp0GBu_Bw8Y=w240-h480-rw
        href: https://uptimerobot.com/dashboard
        description: external
        widget:
          type: uptimerobot
          url: https://api.uptimerobot.com
          key: "{{HOMEPAGE_VAR_UPTIME_ROBOT_API_KEY}}"
- Storage:
    - TrueNAS:
        icon: truenas.svg
        href: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
        description: scale
        widget:
          type: truenas
          url: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
          key: "{{HOMEPAGE_VAR_TRUENAS_API_KEY}}"
    - MinIO:
        icon: minio.svg
        href: "{{HOMEPAGE_VAR_MINIO_URL}}"
        description: object storage
- Media:
    - Plex:
        icon: plex.svg
        href: "{{HOMEPAGE_VAR_PLEX_URL}}"
        description: media server
        widget:
          type: plex
          url: "{{HOMEPAGE_VAR_PLEX_URL}}"
          key: "{{HOMEPAGE_VAR_PLEX_API_TOKEN}}"
    - Tautulli:
        icon: tautulli.svg
        href: "{{HOMEPAGE_VAR_TAUTULLI_URL}}"
        description: plex stats
        widget:
          type: tautulli
          url: "{{HOMEPAGE_VAR_TAUTULLI_URL}}"
          key: "{{HOMEPAGE_VAR_TAUTULLI_API_KEY}}"
    - HDHomerun:
        icon: hdhomerun.png
        href: "{{HOMEPAGE_VAR_HDHOMERUN_URL}}"
        description: flex 4k
        widget:
          type: hdhomerun
          url: "{{HOMEPAGE_VAR_HDHOMERUN_URL}}"
    - Jellyfin:
        icon: jellyfin.svg
        href: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
        description: media server
    - qBittorrent:
        icon: qbittorrent.svg
        href: "{{HOMEPAGE_VAR_QBITTORRENT_URL}}"
        description: torrent client
    - Sonarr:
        icon: sonarr.svg
        href: "{{HOMEPAGE_VAR_SONARR_URL}}"
        description: tv shows
    - Radarr:
        icon: radarr.svg
        href: "{{HOMEPAGE_VAR_RADARR_URL}}"
        description: movies
    - Prowlarr:
        icon: prowlarr.svg
        href: "{{HOMEPAGE_VAR_PROWLARR_URL}}"
        description: indexer manager
    - Bazarr:
        icon: bazarr.svg
        href: "{{HOMEPAGE_VAR_BAZARR_URL}}"
        description: subtitles
- Remote Access:
    - PiKVM:
        icon: https://avatars.githubusercontent.com/u/41749659?s=200&v=4
        href: "{{HOMEPAGE_VAR_PIKVM_URL}}"
        description: remote kvm
    - IPMI:
        icon: https://upload.wikimedia.org/wikipedia/commons/1/1d/Super_Micro_Computer_Logo.svg
        href: "{{HOMEPAGE_VAR_IPMI_1_URL}}"
        description: storinator
    - IPMI:
        icon: https://upload.wikimedia.org/wikipedia/commons/1/1d/Super_Micro_Computer_Logo.svg
        href: "{{HOMEPAGE_VAR_IPMI_2_URL}}"
        description: hl15
    - Netboot:
        icon: https://netboot.xyz/img/nbxyz-laptop.gif
        href: "{{HOMEPAGE_VAR_NETBOOT_URL}}"
        description: network boot utility
    - Tripp Lite:
        icon: https://upload.wikimedia.org/wikipedia/commons/f/f9/Tripp_Lite_logo.svg
        href: "{{HOMEPAGE_VAR_UPS_1_URL}}"
        description: 1500
    - Eaton:
        icon: https://cdn11.bigcommerce.com/s-fg272t4iw0/images/stencil/1280x1280/products/2549/2802/C-12556__63907.1557814942.jpg?c=2
        href: "{{HOMEPAGE_VAR_UPS_2_URL}}"
        description: 5p
- Home Automation:
    - Home Assistant:
        icon: home-assistant.svg
        href: "{{HOMEPAGE_VAR_HOME_ASSISTANT_URL}}"
        description: home
        widget:
          type: homeassistant
          url: "{{HOMEPAGE_VAR_HOME_ASSISTANT_URL}}"
          key: "{{HOMEPAGE_VAR_HOME_ASSISTANT_API_KEY}}"
    - UniFi:
        icon: https://play-lh.googleusercontent.com/DmgQvSdocOrGr0D0rxSBE9sqh23Fw3ck3BgKRN788cZnOKgcZlcEAFRYwmUbp6vMTVI
        href: "{{HOMEPAGE_VAR_UNIFI_PROTECT_URL}}"
        description: protect
    - Scryped:
        icon: https://www.scrypted.app/images/web_hi_res_512.png
        href: "{{HOMEPAGE_VAR_SCRYPTED_URL}}"
        description: mgmt console
    - Broadlink Control:
        icon: https://nwzimg.wezhan.net/contents/sitefiles3606/18030899/images/5430245.png
        href: "{{HOMEPAGE_VAR_BROADLINK_CONTROL_URL}}"
        description: light control
- Other:
    - GitLab:
        icon: gitlab.svg
        href: https://gitlab.com
        description: source code
    - GitHub:
        icon: github.svg
        href: https://github.com
        description: source code
    - Shlink:
        icon: https://shlink.io/images/shlink-logo-blue.svg
        href: "{{HOMEPAGE_VAR_SHLINK_URL}}"
        description: dashboard
