---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Techno Tim Homepage

background:
  image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg
  blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 100 # 0-100

theme: dark
color: slate

useEqualHeights: true

layout:
  Hypervisor:
    header: true
    style: row
    columns: 4
  Containers:
    header: true
    style: row
    columns: 4
  DNS:
    header: true
    style: row
    columns: 4
  Network:
    header: true
    style: row
    columns: 4
  Remote Access:
    header: true
    style: row
    columns: 4
  Storage:
    header: true
    style: row
    columns: 4
  Media:
    header: true
    style: row
    columns: 4
  Home Automation:
    header: true
    style: row
    columns: 4
  Other:
    header: true
    style: row
    columns: 4
