services:
  # IT-Tools - Status Page & Monitoring Server
  it-tools:
    image: corentinth/it-tools
    container_name: it-tools
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - t3_proxy
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.it-tools-rtr.entrypoints=websecure"
      - "traefik.http.routers.it-tools-rtr.rule=Host(`tools.$DOMAINNAME_HS`)"
      # Middlewares
      - "traefik.http.routers.it-tools-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.it-tools-rtr.service=it-tools-svc"
      - "traefik.http.services.it-tools-svc.loadbalancer.server.port=80"