version: "3"

volumes:
  db:
  redis:

services:
  app:
    container_name: kaizoku
    image: ghcr.io/oae/kaizoku:latest
    environment:
      - DATABASE_URL=postgresql://kaizoku:kaizoku@db:5432/kaizoku
      - KAIZOKU_PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PUID=<host user puid>
      - PGID=<host user guid>
      - TZ=Europe/Istanbul
    volumes:
      - $DOCKERDIR/appdata/kaizoku:/config
      - $DATADIR/data/media/manga:/data/manga # Manga is just an example you can have the name you want. See the following
      - $DATADIR/data/media/comics:/data/comics # Use as many as you want
      - $DATADIR/data/media/manhwa:/data/manhwa #
      - $DATADIR/data/media/manhua:/data/manhua #
      - $DATADIR/data/media/books:/data/books #
      - <path_to_logs>:/logs
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data
  db:
    image: postgres:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kaizoku"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=kaizoku
      - POSTGRES_DB=kaizoku
      - POSTGRES_PASSWORD=kaizoku
    volumes:
      - db:/var/lib/postgresql/data
