services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - $DOCKERDIR/appdata/komga:/config
      - $DATADIR/data/media/manga:/data
    environment:
      - TZ=$TZ
    ports:
      - 25600:25600
    user: "1000:1000"
    restart: unless-stopped
